### ISSUE TITLE
Bug reported

### ISSUE THREAD

**Issue by zhangfan0319** [jono-m/OrganoID#5]
Traceback (most recent call last):
  File "/home/fan.zhang/0_software/OrganoID-master/OrganoID.py", line 33, in <module>
    program.RunProgram(args)
  File "/home/fan.zhang/0_software/OrganoID-master/CommandLine/Run.py", line 86, in RunProgram
    parserArgs.gif, parserArgs.batch, parserArgs.analyzeg)
AttributeError: 'Namespace' object has no attribute 'analyzeg'

**Comment by Jay4BioPZ** [comment]
Hi there, I also got the exact same issue when running the segmentation through the command prompt. Could the development team have a look? Appreciate!

**Comment by Jay4BioPZ** [comment]
Just found out how to solve this. It is actually a typo. 
Go to `Run.py`.

`
def RunProgram(self, parserArgs: argparse.Namespace):
from Core.RunPipeline import RunPipeline
...
parserArgs.gif, parserArgs.batch, parserArgs.analyzeg)
`

Simply remove the letter g at the end. It should work.
